services:

  # ---------------------- Bancos PostgreSQL ----------------------
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    networks: [ micros_net ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: product_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    networks: [ micros_net ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    networks: [ micros_net ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------- Infra-estrutura Spring --------------------
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - micros_net
    restart: on-failure

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks: [ micros_net ]
    depends_on:
      discovery-server:
        condition: service_started
    restart: on-failure

  # ---------------------- Micro-serviços --------------------------
  user-service:
    build: ./user-service
    container_name: user-service

    ports:
      - "8081:8081"
    networks: [ micros_net ]
    depends_on:
      config-server:
        condition: service_started        # <-- NOVO
      postgres-user:
        condition: service_healthy
    restart: on-failure

  product-service:
    build: ./product-service
    container_name: product-service

    ports:
      - "8082:8082"
    networks: [ micros_net ]
    depends_on:
      config-server:
        condition: service_started        # <-- NOVO
      postgres-product:
        condition: service_healthy
    restart: on-failure

  order-service:
    build: ./order-service
    container_name: order-service

    ports:
      - "8083:8083"
    networks: [ micros_net ]
    depends_on:
      config-server:
        condition: service_started        # <-- NOVO
      postgres-order:
        condition: service_healthy
      product-service:
        condition: service_started
      user-service:
        condition: service_started
    restart: on-failure

  api-gateway-service:
    build: ./api-gateway-service
    container_name: api-gateway-service

    ports:
      - "8084:8084"
    networks: [ micros_net ]
    depends_on:
      config-server:
        condition: service_started        # <-- NOVO
      discovery-server:
        condition: service_started
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    restart: on-failure

# -----------------------------------------------------------------
networks:
  micros_net:
    driver: bridge
