server:
  port: 8084

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
